version: '3.8'

services:
  app:
    build: .
    ports:
    - "80:80"
    command: npm run start:dev
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      DB_HOST: db 
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      BASE_URL: ${BASE_URL}
      NODE_ENV: development 
    depends_on:
    - db
    volumes:
    - .:/app
    - /app/node_modules 

  db:
    image: postgres:16
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
    - db_data:/var/lib/postgresql/data

volumes:
  db_data: